spring.application.name=HealthSphere
server.port=2030

# Optional connection profile
fabric.connection-profile=D:/HealthSphere-Backend/HealthSphere/connection-org1.json

# MSP credentials (from your local msp folder)
fabric.certificate-path=D:/HealthSphere-Backend/HealthSphere/msp/signcerts/cert.pem
fabric.private-key-dir=D:/HealthSphere-Backend/HealthSphere/msp/keystore

# MSP ID and channel/chaincode info
fabric.msp-id=Org1MSP
fabric.channel=healthchannel
fabric.chaincode=healthsphere

# Peer endpoint and TLS certificate (for peer0.org1.example.com)
fabric.peer-endpoint=localhost:7051
fabric.tls-cert-path=D:/HealthSphere-Backend/HealthSphere/msp/ca.crt


# Enable discovery (optional)
fabric.discovery.enabled=true

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.rishbootdev.healthsphere=DEBUG

# Database (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/healthsphere
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# Application Metadata
healthsphere.version=1.0
healthsphere.developer=rishbootdev
healthsphere.network.org=Org1
